title: Article page
context:
  post-actions: yes
  footer: yes
  post-title: Back to fighting
  post-text: |
    <p>Last week, after almost 2 years without fighting. Past months full of problems, life-changing events, inactivity and a long recovery from an injury; I entered the cage again.</p>
    <p>While I got to focus more on my design career and I even thought for a moment that it may be time to hang the gloves. As time pass I didn’t feel like myself and wasn’t happy with this version of me, I realize that a daily training regime and most importantly… High-level challenges. Make me a better person.</p>
    <p>After 15 years, training and competing has become natural to me, I’ve been having a hard time trying to label myself. I always have troubles answering a regular and often question like “What do you do?”</p>
    <p>Sometimes my response changes depending on the asker or the situation, when I was starting I would say I’m a graphic designer, that changed to web designer and fighter on the side, then to pro fighter and design on the side, later all the recent UI/UX, IX, Product designer craziness. Most of the times I kept the fighting thing to myself.</p>
    <p>Most people advise to choose one thing ride with that label but I just can’t, I know sooner than later I will have to in a way, as you don’t see many middle-aged fighters and I’m sure it will be hard but that’s why I’m trying to enjoy my body as much I can.</p>
    <p>The call arrived at a perfect moment, I was in Florida helping my friend and UFC fighter <a href="https://en.wikipedia.org/wiki/Jessica_Aguilar">Jessica Aguilar</a> for her upcoming fight. So I was having great workouts 2 to 3 times a day while working remotely. If you’re organized enough you can still have a full-time job. I’m not saying is easy but it is doable.</p>
    <p>After I accept the fight had another 2 weeks there, went back to Monterrey for 2 weeks of training there and my last week to Houston with my second family <a href="https://www.facebook.com/4ozFightClub/">4oz. Fight Club</a>. I felt ready to go again.</p>
    <p>I’m not gonna lie, I end up feeling way more nervous than I used to. I kinda get worried about that ring rust everyone talks about. My conditioning too as it wasn’t long since I started training again after my longest inactivity period.</p>
    <p>But the fight was for <a href="https://lfafighting.com/">LFA (Legacy Fighting Alliance)</a>, the best MMA organization not named UFC or Bellator. So I knew it was an amazing opportunity that I had to make the most of.</p>
    <p>An hour before the event started, I went to feel the cage, step in there and visualize the fight. That’s when everything came back, by walking around to get a sense of the dimensions, the texture of the mat in my feet, the sound the grid makes when I push my back against it, the lights on top of me.<br>It just felted good, that I belong here.</p>
    <p>When it was time, I made the walk without any doubts in my mind. I was excited and happy to be there, being part of this with a great challenge in front of me.</p>
    <p>I won, it went to a decision. First 2 rounds were mine then I guess that inactivity hit me as I got really tired but also credit to my opponent who pushed the pace and went there trying to get that finish which I’m thankful for, it was a great test.</p>
    <p>There are many things I could mention, like the 10-hour drive my wife made to arrive at the venue an 1 hour before my fight, true ❤️ that gave me an extra push when I was having some problems in the last round.</p>
    <p>As for the future, I will continue to test myself. I’m not going to choose one career for another, I ’m a better person when I do both.<br>I’m happier and that results in better work, code, designs, solutions, workouts, fights.</p>
    <p>I know I’m not alone so hello to all the ones that can’t only choose one thing and are trying to make it without giving out their multiple passions.<br>And for anyone who’s been thinking about it and hesitating… Just try it please, don’t focus on the results but on your happiness.</p>
  meta-type:
  - post-meta: read
    read: 4 min read
  - meta-link: yes
    post-meta: lang
    lang: Español
  - post-meta: weather
    weather: 73.82°F
  - meta-link: yes
    post-meta: location
    location: 51° N, 0° E
  - meta-link: yes
    post-meta: responses
    responses: 7
  tag-item:
  - tag: Comebacks
  - tag: Martials arts
  - tag: MMA
  - tag: Passions
  - tag: Personal
  reaction:
  - likes: 4
    avatar-item:
    - avatar-src: https://media.ramiroruiz.com/avatars/ramiroruiz/1130549139165634566/4SXqYSCJ_bigger.png
    - avatar-src: https://media.ramiroruiz.com/avatars/karlaleija1/442898714273648641/FZ49joLu_bigger.jpeg
    - avatar-src: https://media.ramiroruiz.com/avatars/clauruizw/1304858610250526722/b90Aclz-_bigger.jpg
  - reposts: 1
    avatar-item:
    - avatar-src: https://media.ramiroruiz.com/avatars/ramiroruiz/1130549139165634566/4SXqYSCJ_bigger.png
    - avatar-src: https://media.ramiroruiz.com/avatars/karlaleija1/442898714273648641/FZ49joLu_bigger.jpeg
  likes: 4
  comments: 2
  comment-items:
  - post-url: https://twitter.com/ramiroruiz/status/1355129784175620098
    post-author: Ramiro Ruiz
    post-author-url: https://twitter.com/ramiroruiz
    post-text: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et ma.
    avatar-classes: c-user-post__avatar u-photo
    avatar-src: https://media.ramiroruiz.com/avatars/ramiroruiz/1130549139165634566/4SXqYSCJ_bigger.png
  - post-url: https://twitter.com/ramiroruiz/status/1355129784175620098
    post-author: Karla Leija
    post-author-url: https://twitter.com/karlaleija1
    post-text: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et ma.
    avatar-classes: c-user-post__avatar u-photo
    avatar-src: https://media.ramiroruiz.com/avatars/karlaleija1/442898714273648641/FZ49joLu_bigger.jpeg
  reposts: 1