title: Figures
variants:
  - name: default
    label: Default
    context:
      img-src: https://images.unsplash.com/photo-1543840721-ff04debc8428?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2670&q=80
      img-caption: Photo by <a href="https://unsplash.com/photos/pkuIDXWSrIU">Luke Slapnicar</a>
  - name: Full width
    context:
      img-src: https://images.unsplash.com/photo-1543840721-ff04debc8428?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2670&q=80
      img-classes: o-figure--full
  - name: Pull-left
    context:
      img-src: https://images.unsplash.com/photo-1543840721-ff04debc8428?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2670&q=80
      img-classes: o-figure--pull-left
  - name: Pull-right
    context:
      img-src: https://images.unsplash.com/photo-1543840721-ff04debc8428?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2670&q=80
      img-classes: o-figure--pull-right