title: Avatar
context:
  avatar-item:
  - avatar-src: https://media.ramiroruiz.com/avatars/ramiroruiz/1130549139165634566/4SXqYSCJ_bigger.png
  - avatar-src: https://media.ramiroruiz.com/avatars/karlaleija1/442898714273648641/FZ49joLu_bigger.jpeg
  - avatar-src: https://media.ramiroruiz.com/avatars/clauruizw/1304858610250526722/b90Aclz-_bigger.jpg
  - avatar-src: https://media.ramiroruiz.com/avatars/charlo_gw/1303767985069281280/wYx5cFsb_bigger.jpg
  - avatar-src: https://media.ramiroruiz.com/avatars/theloversmag/1336602234646384640/u7Ay4lMg_bigger.jpg