title: Avatar
variants:
    - name: default
      label: Default
      context:
        avatar-src: https://media.ramiroruiz.com/avatars/ramiroruiz/1130549139165634566/4SXqYSCJ_bigger.png
    - name: small
      label: Small
      context:
        avatar-src: https://media.ramiroruiz.com/avatars/ramiroruiz/1130549139165634566/4SXqYSCJ_bigger.png
        avatar-size: sm
    - name: large
      label: Large
      context:
        avatar-src: https://media.ramiroruiz.com/avatars/ramiroruiz/1130549139165634566/4SXqYSCJ_bigger.png
        avatar-size: lg